version: '3.8'

services:
  app:
    image: simmuuu/awsfs:latest         
    container_name: awsfs-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    restart: always
